id: P41810294
initial_creation_type: ocr
source_metadata:
  volumes:
    b0c424e6be4243dd9af076087412d700:
      base_file: v107.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་དཀའ་འགྲེལ།
      total_pages: 1891
      volume_number: 107
