id: P41810294
initial_creation_type: ocr
source_metadata:
  volumes:
    5a00ab0b97da488894f9e0e6b1859a66:
      base_file: v107.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་དཀའ་འགྲེལ།
      total_pages: 1891
      volume_number: 107
